import fs from "fs";
import path from "path";

function fail(msg) {
  throw new Error(`[STRICT CREATE FAILED] ${msg}`);
}

function isValidAgentId(agentId) {
  // strict: lowercase letters/numbers/dots only, must include at least one dot
  return /^[a-z0-9]+(\.[a-z0-9]+)+$/.test(agentId);
}

function agentIdToFolder(agentId) {
  // map dots to hyphens for folder names to keep paths simple
  return agentId.replaceAll(".", "-");
}

export function createAgent({ agentId, agentName }) {
  if (!isValidAgentId(agentId)) {
    fail(`Invalid agent id "${agentId}". Use lowercase/digits/dots like "audit.site" or "website.builder".`);
  }
  if (!agentName || agentName.trim().length < 3) {
    fail(`Invalid agent name. Provide a descriptive name.`);
  }

  const repoRoot = process.cwd();
  const templateDir = path.resolve(repoRoot, "agents/_template");
  const registryPath = path.resolve(repoRoot, "agents/registry/agents.json");

  if (!fs.existsSync(templateDir)) fail(`Template folder missing: agents/_template`);
  if (!fs.existsSync(registryPath)) fail(`Registry missing: agents/registry/agents.json`);

  const registry = JSON.parse(fs.readFileSync(registryPath, "utf8"));
  if (registry.agents.some((a) => a.id === agentId)) fail(`Agent already exists in registry: ${agentId}`);

  const folderName = agentIdToFolder(agentId);
  const agentFolderRel = path.join("agents", folderName);
  const agentFolderAbs = path.resolve(repoRoot, agentFolderRel);

  if (fs.existsSync(agentFolderAbs)) fail(`Agent folder already exists: ${agentFolderRel}`);

  fs.mkdirSync(agentFolderAbs, { recursive: true });
  fs.mkdirSync(path.join(agentFolderAbs, "output"), { recursive: true });

  // Build agent.md from template with replacements
  const agentMdTemplate = fs.readFileSync(path.join(templateDir, "agent.md"), "utf8");
  const agentMd = agentMdTemplate.replaceAll("<agent.id>", agentId);

  fs.writeFileSync(path.join(agentFolderAbs, "agent.md"), agentMd, "utf8");

  // Build index.js from template with replacements
  const indexTemplate = fs.readFileSync(path.join(templateDir, "index.js"), "utf8");
  const indexJs = indexTemplate
    .replaceAll("<agent.id>", agentId)
    .replaceAll("<agent-folder>", folderName);

  fs.writeFileSync(path.join(agentFolderAbs, "index.js"), indexJs, "utf8");

  // Register agent
  const newRecord = {
    id: agentId,
    name: agentName,
    folder: agentFolderRel.replaceAll("\\", "/"),
    entry: "index.js",
    description: `${agentName} (generated by core agent)`,
    inputs: [],
    outputs: [`${agentFolderRel.replaceAll("\\", "/")}/output/`],
    tools: [],
    permissions: ["fs.write:agents/**/output"],
    status: "active"
  };

  registry.agents.push(newRecord);
  fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2) + "\n", "utf8");

  return {
    ok: true,
    created: {
      id: agentId,
      folder: newRecord.folder
    }
  };
}
